### ISSUE TITLE
d3-hexjson - simple design: good, fully featured: worse?

### ISSUE THREAD

**Issue by psychemedia** [olihawkins/d3-hexjson#3] opened 2017-06-30 23:13 UTC
Hi Oli

I noticed in https://github.com/olihawkins/d3-hexjson/issues/2 you mentioned this isn't a fully featured plugin, but how to identify richer features, and find alternative routes to them, is an interesting question I think, especially if viewing things like this package as a contribution to a publishing system that makes use of plugins to generate HTML charts in reproducible research style workflows using things like RStudio/Rmd/HTMLwidgets/knitr or the Jupyter ecosystem, for example.

As a specific example, I have started working up an R/knit *htmlwidget*, [`htmlwidget-hexjson`](https://github.com/psychemedia/htmlwidget-hexjson) around this package. While that package supports hexmap features, such as changing hex colours, or labels, it doesn't require that `d3-hexjson` package supports those.

Instead, a parameterised HTML/JS template can be populated from an R script which *does* wrangle the various parameter values. Rather than having a complex, feature rich Javascript charter, we can use a simple charter (your `d3-hexjson` plugin), a parameterised template, and a relatively simple  set of R routines that populate the template.

The complexity comes from the combination of simple parts, with separation of concerns.

Another way of viewing it could be that the R code/HTML'n'JS template identifies and prototypes where useful plasticity in a more complex, feature rich `d3-hexjson` plugin might be useful?

It's one to ponder, I think, if viewing such plugins as part of a wider publishing system, both in terms of architecture but also design. For example, how much different would my `hexjsonwidget` code if your `d3-hexjson` plugin had more parameters/complexity; or components in an interactive Shiny dashboard (trying the `hexjsonwidget` in a Shiny context is on my TODO list) ; how would  Python based *ipywidget* or plotly/dash usecases built around the current `d3-hexjson` plugin, or a richer version of it, compare, and so on?

**Comment by ronaldkunenborg** [comment] 2017-07-01 16:29
Hi, 

I agree that keeping things as simple as possible is a good designgoal for any plugin.  However, I do think there is room for a few small extensions in this plugin:
- Support for axial layouts;
- Support for variating the radius for hexes, similar to d3-hexbin and for the same purpose - perhaps even adding hexbinning functionality. 

I'm currently working on the first one, based on a proposed change to the HexJSON description that includes more layout options.

Disclaimer: I'm not Oli and I don't speak for him, so he may have a (quite) different opinion about this.

**Comment by psychemedia** [comment] 2017-07-01 17:39
Hi Ronald

Re: *based on a proposed change to the HexJSON description*, where are those proposals being discussed? I'd be interested in seeing what's being suggested and the process by which any changes get adopted.

**Comment by ronaldkunenborg** [comment] 2017-07-01 21:47
Hi, I discussed my proposal with Oli. There is no process at the ODI as far as I know, ODI doesn't answer my email on this topic nor do they respond to my pull request. I created a pull request for https://github.com/odileeds/hexmaps (hexjson.html), you can see my version in the repo clone here: https://github.com/ronaldkunenborg/hexmaps (hexjson.html) - make sure you switch to the "hexjson" branch, not the main branch, otherwise you won't see any change.

Direct link: https://github.com/ronaldkunenborg/hexmaps/blob/hexjson/hexjson.html

I can summarize the very minor changes as follows:
- Added version property ("x,y") (semantic versioning standard) to facilitate future changes;
- Added "axial-r" and "axial-q" as possible layouts (the layouts should now cover most useful coordinate systems); 
- Added minCoordinates property to define the location of the hexagon with the smallest coordinates. This gives the HexJSON file the ability to define how the file should be displayed and which hexagon is linked to which neighbours and in what way. 
Note that the last propertyname also implies camelCase for further properties.

Feel free to suggest changes, the pull request is still open.

**Comment by olihawkins** [comment] 2017-07-02 08:51
Hello both,

This seems like a good opportunity to set out the goals and constraints governing the projects that I post on GitHub and what you can expect from me in terms of support and contributions.

The single most important constraint affecting the code that I open source here is time: I don't have much at all. My job imposes significant demands on my time and attention that I cannot control.

Typically the code that I post here is a generalised solution to a problem that I need to solve for a specific purpose (see the mnis library for another example). My main motive in creating a general solution is to save myself work later on when I need to do something similar in future.

My approach to generalisation is to implement the core functionality that I need for my specific purpose in a way that allows it to be extended to other uses in future, either by me or by other people. I don't try to anticipate what those uses will be and I don't typically take a view on whether a given use is valid or not.

Three things follow from the above. First, if people find new uses for my code then I want to accommodate that, but I can't promise that I will have the time to actively support it by adding new functionality.

Second, I am committed to maintaining backwards and forwards compatibility and to squashing bugs. I will try hard to ensure that the code keeps working as described as the world changes around it. I will also resist adding new features if doing so narrows the functionality that was originally provided.

Third, I am strongly in favour of modularity. Adding new features to a library that are not essential to its core functionality only adds unnecessary bloat for users that don't need those features. This is particularly true for client-side JavaScript libraries. Mike Bostock had good reasons for making D3 v4 modular. If you need additional functionality that is not provided by the library for a specific purpose then you can always take it as a dependency as part of a new project.

So where does this leave d3-hexjson? Despite what I say in the third point above, I am sympathetic to the idea that HexJSON could benefit from supporting axial layouts. The current HexJSON spec seems a bit too narrow in that respect. However, I am reluctant to add support to d3-hexjson for anything that is not part of the HexJSON spec. I don't want to own the spec and I certainly don't want to create a rival spec.

**Comment by psychemedia** [comment] 2017-07-02 11:29
<blockquote>My approach to generalisation is to implement the core functionality that I need for my specific purpose in a way that allows it to be extended to other uses in future, either by me or by other people. I don't try to anticipate what those uses will be and I don't typically take a view on whether a given use is valid or not.</blockquote>

+1 on that. And your follow up. My original point was to try to tease out some of the key things that make something useful, in a pragmatic way, like the `d3-hexjson` library, and think carefully about where extensions might fit in.

Playing with HTMLwidgets for the first time, the HTML template is actually the place where a lot of flexibility can be accommodated, even with a simple `hexjson` spec?

**Comment by ronaldkunenborg** [comment] 2017-07-02 14:02
Okay, that's a nice and clear statement. Good points.

"However, I am reluctant to add support to d3-hexjson for anything that is not part of the HexJSON spec. I don't want to own the spec and I certainly don't want to create a rival spec."

I agree in principle. However, if they never respond to questions or pull requests this will become problematic in the longer run. For now I can wait and see what happens though.

So I'm going to proceed with the code that was going to use the axial layout and change it a bit so it uses the current standard layout. That'll be a bit less elegant but should still work as intended.

**Closed as completed** 2018-01-02 14:36 UTC
